INSERT INTO users (name, email, password, geolocation, avatar, active) VALUES ('Jay Martens', 'martensjay93@gmail.com', '$2b$10$HBjBHNCg80cTsG5MAuc9PuL6xDecjV0eMloX.ibE4nnjJ96NWTcMq', '{"lat": 43.6494535, "lng": -79.3863506}', 'https://www.flaticon.com/svg/static/icons/svg/3530/3530223.svg', TRUE);
INSERT INTO users (name, email, password, geolocation, avatar, active) VALUES ('Decland Bobby', 'declanbobby@gmail.com', '$2b$10$HBjBHNCg80cTsG5MAuc9PuL6xDecjV0eMloX.ibE4nnjJ96NWTcMq', '{"lat": 43.6795231, "lng": -79.4100136}', 'https://www.flaticon.com/svg/static/icons/svg/3530/3530140.svg', TRUE);
INSERT INTO users (name, email, password, geolocation, avatar, active) VALUES ('Jules Potato', 'potatofarmer88@gmail.com', '$2b$10$HBjBHNCg80cTsG5MAuc9PuL6xDecjV0eMloX.ibE4nnjJ96NWTcMq', '{"lat": 43.6592934, "lng": -79.4035223}', 'https://www.flaticon.com/svg/static/icons/svg/3531/3531023.svg', TRUE);
INSERT INTO users (name, email, password, geolocation, avatar, active) VALUES ('Camilio Gomez', 'bestmusician@hotmail.com', '$2b$10$HBjBHNCg80cTsG5MAuc9PuL6xDecjV0eMloX.ibE4nnjJ96NWTcMq', '{"lat": 43.7237857, "lng": -79.38865}', 'https://www.flaticon.com/svg/static/icons/svg/3529/3529992.svg', TRUE);
INSERT INTO users (name, email, password, geolocation, avatar, active) VALUES ('Angel Overwatch', 'mercymain@hotmail.com', '$2b$10$HBjBHNCg80cTsG5MAuc9PuL6xDecjV0eMloX.ibE4nnjJ96NWTcMq', '{"lat": 43.6541272, "lng": -79.3524023}', 'https://www.flaticon.com/svg/static/icons/svg/3468/3468273.svg', FALSE);
INSERT INTO users (name, email, password, geolocation, avatar, active) VALUES ('Juan Huan', 'flowfordays@gmail.com', '$2b$10$HBjBHNCg80cTsG5MAuc9PuL6xDecjV0eMloX.ibE4nnjJ96NWTcMq', '{"lat": 43.6508634, "lng": -79.477651}', 'https://www.flaticon.com/svg/static/icons/svg/3530/3530247.svg', FALSE);

INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('1', '2', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('1', '3', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('1', '4', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('1', '5', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('1', '6', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('2', '1', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('2', '3', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('2', '4', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('2', '5', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('2', '6', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('3', '1', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('3', '2', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('3', '4', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('3', '5', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('3', '6', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('4', '1', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('4', '2', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('4', '3', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('4', '5', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('4', '6', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('5', '1', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('5', '2', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('5', '3', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('5', '4', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('5', '6', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('6', '1', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('6', '2', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('6', '3', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('6', '4', TRUE);
INSERT INTO friends (user_id, friend_id, confirmed) VALUES ('6', '5', TRUE);